# Documentation at https://www.netlify.com/docs/netlify-toml-reference/
[build]
  command = "./build.sh --build"
  publish = "_site/"

[build.environment]
  RUBY_VERSION = "3.2.2"

# Copied from https://answers.netlify.com/t/jekyll-site-uses-absolute-urls-deploy-previews-navigate-to-main-site/8441/12
[context.deploy-preview]
  command = "printf \"url: %s\" \"$DEPLOY_PRIME_URL\" > _config_netlify.yml; ./build.sh --build --extra-config $(pwd)/_config_netlify.yml"
